# Generated by Django 4.1.5 on 2023-02-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('surname', models.TextField(max_length=40)),
                ('age', models.IntegerField()),
                ('photo', models.FilePathField(path='static/nikita/images/')),
            ],
        ),
    ]
