# Generated by Django 4.1.5 on 2023-02-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
