# Generated by Django 4.1.5 on 2023-02-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikita', '0002_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.FilePathField(path='/Users/nikitalutsai/VScodeProjects/practise1/nikita/static/nikita/images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
