# Generated by Django 4.1.5 on 2023-02-05 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('surname', models.TextField(max_length=20)),
                ('age', models.PositiveIntegerField(verbose_name=django.core.validators.MaxValueValidator(120, 'Please, enter a valid age'))),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
